Resources:
  WebServerSG: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access on ports 80 and 22
      GroupName: Okulda_yaptim
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: Mywep-01
      VpcId: vpc-023047f6868a7bde7

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro  
      SubnetId: subnet-0a8a163bd4ca9f469
      SecurityGroupIds:
        - !Ref WebServerSG
      KeyName: Flaskdemo
      ImageId: ami-0022f774911c1d690
      Tags:
        - Key: Name
          Value: Proje-web server
      UserData: 
        Fn::Base64:
          !Sub |
          #!/bin/bash -xe
          sudo su
          yum update -y
          yum install -y httpd
          cd /var/www/html
          wget https://github.com/yucelimmm/CF-Template/archive/main.zip
          unzip main.zip
          cp -r CE-Template-main/* /var/www/html/
          rm -rf techmax-main main.zip
          systemctl enable httpd 
          systemctl start httpd
